### ISSUE TITLE
fatal error: map: No such file or directory

### ISSUE THREAD

**Issue by Hsiao-Jan** [SGX-Cloud/migration#2]
hi,
   when i try to `make -B all` ,I get the following error.
```
/opt/intel/sgxsdk/bin/x64/sgx_edger8r lib_migration.edl --search-path /opt/intel/sgxsdk/include --search-path ../../sgx-utils/libs/lib_la --trusted-dir ./generated --untrusted-dir ./generated
GEN  =>  generated/lib_migration_t.c
CC   <=  generated/lib_migration_t.c
/opt/intel/sgxsdk/bin/x64/sgx_edger8r lib_migration.edl --search-path /opt/intel/sgxsdk/include --search-path ../../sgx-utils/libs/lib_la --trusted-dir ./generated --untrusted-dir ./generated
GEN  =>  generated/lib_migration_t.h
In file included from trusted/marshalling.cpp:54:0:
../../sgx-utils/libs/lib_la/trusted/tla.h:49:15: fatal error：map：No such file or directory.
 #include <map>
               ^
compilation terminated
```

My os :
Linux version 3.10.0-957.27.2.el7.x86_64 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) )

release:
CentOS Linux release 7.6.1810 (Core)

I tried compiling a xxx.cpp with  `#include <map>`  and then compiling with the command `g++ xxx.cpp -std=c++11`, everything is ok.

How can I solve this problem?

**Comment by fritzalder** [comment]
Hi, and thanks for your interest.
The problem seems to be that newer SGX SDKs changed the name of the standard libraries. I pushed this commit https://github.com/SSGAalto/sgx-migration/commit/4dd8c4d9d9ffac1155a3161e9a0321b0f4a4377a . Can you verify that this works for you? 

Please remember that this was a research project, so I just made sure that it compiles and could not verify that it still works properly. But I can work with you if you encounter more issues.

Cheers,
Fritz

**Comment by Hsiao-Jan** [comment]
Hi Fritz,

Thanks for your reply.It works. I have compiled it successfully.
However, I haven't had time to run the test at this time. If there are follow-up problems, I hope you can help me.

Thanks again very much for your reply！

**Comment by Hsiao-Jan** [comment]
I have another question. When I read the sgx-migration paper, the paper involves the source computer and the destination computer. Does this mean that data migration can be performed between two computers?

**Comment by fritzalder** [comment]
If you look at the sample app, it uses simple TCP to determine where to send the data so it already supports migration between systems. Keep in mind that the Migration Enclave should be local while the destination can be remote.

I suggest you create a new issue if you have more problems so that I can close this one.
